apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsproxy
  labels:
    app: dnsproxy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: dnsproxy
  template:
    metadata:
      labels:
        app: dnsproxy
    spec:
      containers:
        - name: dnsproxy
          image: localhost/dnsproxy:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 53
          volumeMounts: # use avahi from host
            - name: dbus
              mountPath: /run/dbus
            - name: avahi-socket
              mountPath: /run/avahi-daemon/socket
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: dbus
          hostPath:
            path: /var/run/dbus
            type: Directory
        - name: avahi-socket
          hostPath:
            path: /var/run/avahi-daemon/socket
            type: Socket

---

apiVersion: v1
kind: Service
metadata:
  name: dnsproxy-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: dnsproxy
  loadBalancerIP: 192.168.1.242
